using System;

namespace Wotc.Mtga.Hangers;

[Flags]
public enum ParameterizedInjectors
{
	NONE = 0,
	INJECT_MANA = 1,
	INJECT_LINKED_INFO = 2,
	INJECT_CONTROLLER_GY_PERMANENTS = 4,
	INJECT_NUMERAL = 8,
	INJECT_FAKE_NUMERAL = 0x10,
	INJECT_MANA_TITLE = 0x20,
	INJECT_MANA_COLOR = 0x40,
	INJECT_X = 0x80,
	INJECT_STATION_CHARGE_REQUIREMENT = 0x100,
	INJECT_NUMERAL_MANA_SYMBOLS = 0x200,
	INJECT_NUMERAL_CARD_NAME = 0x400
}
