return Creature("Lys Alana Informant")
    :mana_cost("{1}{G}")
    :colors({"Green"})
    :subtypes({"Elf", "Scout"})
    :power_toughness(3, 1)
    :oracle_text("When this creature enters or dies, surveil 1. (Look at the top card of your library. You may put it into your graveyard.)")
    :flavor_text("While they are no longer the dominant power on Lorwyn, elves still revel in looking down on others.")
    :on_enter_battlefield(function(ctx, event)
        ctx:surveil(event.player_id, 1)
    end)
    :on_death(function(ctx, event)
        ctx:surveil(event.player_id, 1)
    end)
    :build()
