return Creature("Scourge of the Undercity")
    :mana_cost("{1}{B}")
    :colors({"Black"})
    :subtypes({"Gorgon", "Vampire"})
    :power_toughness(2, 1)
    :lifelink()
    :oracle_text("Lifelink\nWhen Scourge of the Undercity enters, another creature you control gains lifelink until end of turn.")
    :flavor_text("Her hunger for blood is matched only by her hunger for vengeance.")
    :on_enter_battlefield(function(ctx, event)
        local target = ctx:choose_target(event.player_id, "creature_you_control")
        if target == 0 then return end
        ctx:grant_keyword(target, "Lifelink")
        ctx:register_delayed_trigger(target, "on_end_of_turn", "remove_lifelink", function(ctx, event)
            ctx:remove_keyword(target, "Lifelink")
        end)
    end)
    :build()
