return Creature("Baleful Force")
    :mana_cost("{5}{B}{B}{B}")
    :colors({"Black"})
    :subtypes({"Elemental"})
    :power_toughness(7, 7)
    :oracle_text("At the beginning of each upkeep, you draw a card and you lose 1 life.")
    :flavor_text("'As with any malevolent being, the trick is knowing how long you can afford to keep it in your service.'\n -Liliana Vess")
    :on_beginning_of_upkeep(function(ctx, event)
        ctx:draw_cards(event.player_id, 1)
        ctx:lose_life(event.player_id, 1)
    end)
    :build()
