return Creature("Ankle Biter")
    :mana_cost("{G}")
    :colors({"Green"})
    :subtypes({"Snake"})
    :deathtouch()
    :power_toughness(1, 1)
    :oracle_text("Deathtouch")
    :flavor_text("Little tip newcomer. Give your boots a shake in the morning before you put them on\n-Annie Flash, to Kellan")
    :build()
