return Creature("Dawn's Light Archer")
    :mana_cost("{2}{G}")
    :colors({"Green"})
    :subtypes({"Elf", "Archer"})
    :flash()
    :reach()
    :power_toughness(4, 2)
    :oracle_text("Flash\nReach")
    :flavor_text("Archery is beauty in action. Your stance, your draw, your aim, and your release. All must be a single harmonious motion.")
    :build()
