return Creature("Lumberknot")
    :mana_cost("{2}{G}{G}")
    :colors({"Green"})
    :subtypes({"Treefolk"})
    :hexproof()
    :power_toughness(1, 1)
    :oracle_text("Hexproof (This creature can't be the target of spells or abilities your opponents control)\nWhenever a creature dies, put a +1/+1 counter on this creature")
    :flavor_text("Animated by geists fused in its oak, it hungers for more life to add to its own core.")
    :on_another_creature_dies(function(ctx, event)
        ctx:add_counter(event.source_id, "+1/+1", 1)
    end)
    :build()
