return Creature("Vampire of the Dire Moon")
    :mana_cost("{B}")
    :colors({"Black"})
    :subtypes({"Vampire"})
    :power_toughness(1, 1)
    :lifelink()
    :deathtouch()
    :oracle_text("Lifelink\nDeathtouch")
    :flavor_text("This place suits me: craven authorities and plentiful prey.")
    :build()
