return Creature("Elvish Mystic")
    :mana_cost("{G}")
    :colors({"Green"})
    :subtypes({"Elf", "Druid"})
    :power_toughness(1, 1)
    :oracle_text("{T}:Add {G}.")
    :flavor_text("Life grows everywhere. My kin merely find those places where it grows strongest.\n-Nissa Revane")
    :activated_ability("{T}", "{T}: add {G}", function(ctx, event)
        ctx:add_mana(event.player_id, "G", 1)
    end, false, true)
    :build()
